allowBuilds:
  '@parcel/watcher': true
  esbuild: true
  unrs-resolver: true
minimumReleaseAgeExclude:
  - '@unveil/identity'
  - 'vue-data-ui'
  - '@unveil/vk'

overrides:
  '@unveil/vk>@unveil/identity': '2.0.5-beta.1'
